/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supermarket;

/**
 *
 * @author Edward Murithi
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        totalCost = new javax.swing.JTextField();
        cashtext = new javax.swing.JTextField();
        changetext = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        paidCash = new javax.swing.JTextField();
        VAT = new javax.swing.JTextField();
        preTax = new javax.swing.JTextField();
        prevat = new javax.swing.JLabel();
        DCT = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        rice = new javax.swing.JCheckBox();
        maize = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        num5 = new javax.swing.JLabel();
        num1 = new javax.swing.JLabel();
        Q1 = new javax.swing.JTextField();
        Q2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        ricetext = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        maizetext = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        sugar = new javax.swing.JCheckBox();
        wheat = new javax.swing.JCheckBox();
        oil = new javax.swing.JCheckBox();
        Q3 = new javax.swing.JTextField();
        Q4 = new javax.swing.JTextField();
        Q5 = new javax.swing.JTextField();
        sugartext = new javax.swing.JLabel();
        wheattext = new javax.swing.JLabel();
        oiltext = new javax.swing.JLabel();
        num2 = new javax.swing.JLabel();
        num3 = new javax.swing.JLabel();
        num4 = new javax.swing.JLabel();
        soap = new javax.swing.JCheckBox();
        num6 = new javax.swing.JLabel();
        Q6 = new javax.swing.JTextField();
        soaptext = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel16.setText("Total");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, 20));

        jLabel17.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel17.setText("Cash paid");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 80, 20));

        totalCost.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        totalCost.setBorder(null);
        totalCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalCostActionPerformed(evt);
            }
        });
        jPanel2.add(totalCost, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 330, 80, 20));

        cashtext.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        cashtext.setForeground(new java.awt.Color(153, 0, 51));
        jPanel2.add(cashtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 140, 30));

        changetext.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        changetext.setForeground(new java.awt.Color(255, 0, 51));
        jPanel2.add(changetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 140, 40));

        jLabel19.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel19.setText("Change");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 60, 20));

        jLabel20.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel20.setText("AMOUNT");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 70, 20));

        jLabel22.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel22.setText("Discount");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 80, 20));

        jLabel23.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel23.setText("PRE-VAT");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 70, 20));

        jLabel24.setFont(new java.awt.Font("Bell MT", 0, 14)); // NOI18N
        jLabel24.setText("VAT");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 50, 20));

        paidCash.setFont(new java.awt.Font("Sitka Display", 1, 16)); // NOI18N
        paidCash.setBorder(null);
        paidCash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                paidCashMouseEntered(evt);
            }
        });
        paidCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paidCashActionPerformed(evt);
            }
        });
        jPanel2.add(paidCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 140, 30));

        VAT.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        VAT.setBorder(null);
        jPanel2.add(VAT, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 80, 20));

        preTax.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        preTax.setBorder(null);
        jPanel2.add(preTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 70, 20));

        prevat.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jPanel2.add(prevat, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 60, 20));

        DCT.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        DCT.setBorder(null);
        DCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DCTActionPerformed(evt);
            }
        });
        jPanel2.add(DCT, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 140, 20));

        jButton1.setBackground(new java.awt.Color(102, 102, 255));
        jButton1.setFont(new java.awt.Font("Agency FB", 1, 20)); // NOI18N
        jButton1.setForeground(new java.awt.Color(204, 0, 0));
        jButton1.setText("Compute");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, 140, 30));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator2.setForeground(new java.awt.Color(51, 51, 51));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 310, 10));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 330, 430));

        jLabel1.setFont(new java.awt.Font("Sitka Display", 1, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Welcome To Magunas Main Branch Online Shop");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, 680, 60));

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rice.setBackground(new java.awt.Color(204, 255, 255));
        rice.setText("Rice");
        jPanel3.add(rice, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        maize.setBackground(new java.awt.Color(204, 255, 255));
        maize.setText("Maize flour");
        jPanel3.add(maize, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel9.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel9.setText("Items");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 60, 20));

        num5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        num5.setText("5");
        jPanel3.add(num5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        num1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        num1.setText("1");
        jPanel3.add(num1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 10, -1));

        Q1.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        Q1.setBorder(null);
        jPanel3.add(Q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 70, -1));

        Q2.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        Q2.setBorder(null);
        jPanel3.add(Q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 70, -1));

        jLabel12.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel12.setText("Qty(kg)");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 70, 20));

        ricetext.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jPanel3.add(ricetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 260, 60, 20));

        jLabel15.setFont(new java.awt.Font("Sitka Display", 0, 18)); // NOI18N
        jLabel15.setText("Amount");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 70, 20));

        maizetext.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jPanel3.add(maizetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 60, 20));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 310, 10));

        sugar.setBackground(new java.awt.Color(204, 255, 255));
        sugar.setText("Sugar");
        jPanel3.add(sugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        wheat.setBackground(new java.awt.Color(204, 255, 255));
        wheat.setText("Wheat flour");
        wheat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheatActionPerformed(evt);
            }
        });
        jPanel3.add(wheat, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        oil.setBackground(new java.awt.Color(204, 255, 255));
        oil.setText("Cooking oil");
        jPanel3.add(oil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        Q3.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        Q3.setBorder(null);
        jPanel3.add(Q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 70, -1));

        Q4.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        Q4.setBorder(null);
        jPanel3.add(Q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 70, -1));

        Q5.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        Q5.setBorder(null);
        jPanel3.add(Q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 70, -1));

        sugartext.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jPanel3.add(sugartext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 60, 20));

        wheattext.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jPanel3.add(wheattext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 60, 20));

        oiltext.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jPanel3.add(oiltext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 60, 20));

        num2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        num2.setText("2");
        jPanel3.add(num2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 10, -1));

        num3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        num3.setText("3");
        jPanel3.add(num3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 10, -1));

        num4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        num4.setText("4");
        jPanel3.add(num4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 10, -1));

        soap.setBackground(new java.awt.Color(204, 255, 255));
        soap.setText("Soap");
        jPanel3.add(soap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        num6.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        num6.setText("6");
        jPanel3.add(num6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        Q6.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        Q6.setBorder(null);
        jPanel3.add(Q6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 70, -1));

        soaptext.setFont(new java.awt.Font("Sitka Display", 1, 14)); // NOI18N
        jPanel3.add(soaptext, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 300, 60, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/icons8_Return_Purchase_26px.png"))); // NOI18N
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 40, 40));

        jButton2.setBackground(new java.awt.Color(255, 204, 0));
        jButton2.setFont(new java.awt.Font("Berlin Sans FB", 0, 16)); // NOI18N
        jButton2.setText("Add Cart");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(213, 383, 90, 30));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 340, 430));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/male_user_50px.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, 50, 120));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/supermarket/images (7).jpeg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 560));

        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 310, 80, 30));

        jLabel6.setFont(new java.awt.Font("Vivaldi", 1, 25)); // NOI18N
        jLabel6.setText("Edward254 devOps");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 570, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paidCashMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_paidCashMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_paidCashMouseEntered

    private void paidCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paidCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paidCashActionPerformed

    private void DCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DCTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DCTActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        /*Setting variables and change calculation*/
        double cost = Double.parseDouble(paidCash.getText());
        double cash = Double.parseDouble(cashtext.getText());
        double Remaining = cash - cost;

        /*Change decision*/
        if (cash >= cost) {
            String Remaining_amount = String.format("%.2f", Remaining);
            changetext.setText(Remaining_amount);
        } else {
            changetext.setText("Insufficient\n Cash");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void wheatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wheatActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        /*Control Structure*/
 /*Maize*/
        if (maize.isSelected() == (true)) {
            double Qty1 = Double.parseDouble(Q1.getText());
            double price = Qty1 * 187;
            String cost = String.format("%.2f", price);
            maizetext.setText(cost);
        } else {
            maizetext.setText("0");
        }
        /*Sugar*/
        if (sugar.isSelected() == (true)) {
            double Qty2 = Double.parseDouble(Q2.getText());
            double price = Qty2 * 260;
            String cost = String.format("%.2f", price);
            sugartext.setText(cost);
        } else {
            sugartext.setText("0");
        }
        /*Wheat*/
        if (wheat.isSelected() == (true)) {
            double Qty3 = Double.parseDouble(Q3.getText());
            double price = Qty3 * 198;
            String cost = String.format("%.2f", price);
            wheattext.setText(cost);
        } else {
            wheattext.setText("0");
        }
        /*Cooking oil*/
        if (oil.isSelected() == (true)) {
            double Qty4 = Double.parseDouble(Q4.getText());
            double price = Qty4 * 750;
            String cost = String.format("%.2f", price);
            oiltext.setText(cost);
        } else {
            oiltext.setText("0");
        }
        /*Rice*/
        if (rice.isSelected() == (true)) {
            double Qty5 = Double.parseDouble(Q5.getText());
            double price = Qty5 * 210;
            String cost = String.format("%.2f", price);
            ricetext.setText(cost);
        } else {
            ricetext.setText("0");
        }
        /*Soap*/
        if (soap.isSelected() == (true)) {
            double Qty6 = Double.parseDouble(Q6.getText());
            double price = Qty6 * 180;
            String cost = String.format("%.2f", price);
            soaptext.setText(cost);
        } else {
            soaptext.setText("0");
        }

        /*Initializing or setting the variables*/
        double maize_price = Double.parseDouble(maizetext.getText());
        double sugar_price = Double.parseDouble(sugartext.getText());
        double wheat_price = Double.parseDouble(wheattext.getText());
        double oil_price = Double.parseDouble(oiltext.getText());
        double rice_price = Double.parseDouble(ricetext.getText());
        double soap_price = Double.parseDouble(soaptext.getText());
        
        /*Gross price calculations*/
        double gross_price = maize_price + sugar_price + wheat_price + oil_price + rice_price + soap_price;
        double tax = gross_price * 0.16;
        double pre_tax = gross_price - tax;

        /*Converting the int variables to String variable*/
        String total_price = String.format("%.2f", gross_price);
        String added_tax = String.format("%.2f", tax);
        String taxable = String.format("%.2f", pre_tax);

        /*Computations*/
        totalCost.setText(total_price);
        VAT.setText(added_tax);
        preTax.setText(taxable);

        /*Discount computations*/
        if (gross_price > 1000) {
            double net_price = gross_price * 0.98;
            double discount = 0.02 * gross_price;
            String payable_amount = String.format("%.2f", net_price);
            String discount_earned = String.format("%.2f", discount);

            paidCash.setText(payable_amount);
            DCT.setText(discount_earned);
        } else {
            double net_price = gross_price;
            String payable_amount = String.format("%.2f", net_price);
            paidCash.setText(payable_amount);
            DCT.setText("No Discount!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void totalCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalCostActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DCT;
    private javax.swing.JTextField Q1;
    private javax.swing.JTextField Q2;
    private javax.swing.JTextField Q3;
    private javax.swing.JTextField Q4;
    private javax.swing.JTextField Q5;
    private javax.swing.JTextField Q6;
    private javax.swing.JTextField VAT;
    private javax.swing.JTextField cashtext;
    private javax.swing.JTextField changetext;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JCheckBox maize;
    private javax.swing.JLabel maizetext;
    private javax.swing.JLabel num1;
    private javax.swing.JLabel num2;
    private javax.swing.JLabel num3;
    private javax.swing.JLabel num4;
    private javax.swing.JLabel num5;
    private javax.swing.JLabel num6;
    private javax.swing.JCheckBox oil;
    private javax.swing.JLabel oiltext;
    private javax.swing.JTextField paidCash;
    private javax.swing.JTextField preTax;
    private javax.swing.JLabel prevat;
    private javax.swing.JCheckBox rice;
    private javax.swing.JLabel ricetext;
    private javax.swing.JCheckBox soap;
    private javax.swing.JLabel soaptext;
    private javax.swing.JCheckBox sugar;
    private javax.swing.JLabel sugartext;
    private javax.swing.JTextField totalCost;
    private javax.swing.JCheckBox wheat;
    private javax.swing.JLabel wheattext;
    // End of variables declaration//GEN-END:variables
}
